import { useCallback, useEffect, useState } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { api, setAdminToken } from '../api/client';
import { PAYMENT_STATUS_LABELS } from '../lib/automotiveLabels';
import { formatMoneyMinor } from '../lib/payment';
import { userError } from '../lib/userError';
import type { AdminPayment, PaymentStatus } from '../types';

const filters: Array<['' | PaymentStatus, string]> = [['','Все'],['pending','Ожидают'],['paid','Оплачены'],['failed','Ошибки'],['cancelled','Отменены']];
const providerLabel = (provider: string) => provider === 'demo' ? 'Демонстрационный' : 'Внешний';

export function PaymentsAdminPage() {
  const demo = useLocation().pathname.startsWith('/demo/');
  const [items, setItems] = useState<AdminPayment[]>([]); const [status, setStatus] = useState<'' | PaymentStatus>(''); const [error, setError] = useState(''); const [token, setToken] = useState('');
  const [loading, setLoading] = useState(true);
  const load = useCallback(() => { setLoading(true); return api.getAdminPayments(demo, status).then((data) => { setItems(data); setError(''); }).catch((cause) => setError(userError(cause, demo ? 'Не удалось загрузить демо-платежи.' : 'Введите токен администратора для доступа.'))).finally(() => setLoading(false)); }, [demo,status]);
  useEffect(() => { void load(); }, [load]);
  return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">{demo ? 'Демо-кабинет · только просмотр' : 'Кабинет администратора'}</p><h1>Платежи</h1></div><nav className="admin-nav"><Link to={`${demo ? '/demo' : ''}/admin`}>Объявления</Link><Link to="/">Открыть каталог</Link></nav></header>{error && !demo && <form className="token-form" onSubmit={(event) => { event.preventDefault(); setAdminToken(token); void load(); }}><label><span>Токен администратора</span><input type="password" autoComplete="current-password" value={token} onChange={(event) => setToken(event.target.value)} /></label><button className="primary-button">Войти</button></form>}{error && demo && <div className="empty-state error-state" role="alert">{error}</div>}<div className="admin-filters">{filters.map(([value,label]) => <button className={status === value ? 'is-active' : ''} type="button" key={value} onClick={() => setStatus(value)}>{label}</button>)}</div>{loading ? <div className="loading">Загрузка…</div> : !error && !items.length ? <div className="empty-state">Платежей с таким статусом пока нет.</div> : error ? null : <div className="admin-table-wrap"><table><thead><tr><th>ID</th><th>Объявление</th><th>Пользователь</th><th>Тариф</th><th>Сумма</th><th>Статус</th><th>Тип оплаты</th><th>Создан</th><th>Оплачен</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><Link to={`${demo ? '/demo' : ''}/admin/payments/${item.id}`}>{item.id}</Link></td><td>{item.listing?.title ?? `Объявление №${item.listingId}`}</td><td>{item.customer?.name ?? `Пользователь №${item.customerId}`}</td><td>{item.tariff.name}</td><td>{formatMoneyMinor(item.amountMinor,item.currency)}</td><td><span className={`payment-state payment-${item.status}`}>{PAYMENT_STATUS_LABELS[item.status]}</span></td><td>{providerLabel(item.provider)}</td><td>{new Date(item.createdAt).toLocaleString('ru-RU')}</td><td>{item.paidAt ? new Date(item.paidAt).toLocaleString('ru-RU') : '—'}</td></tr>)}</tbody></table></div>}</main>;
}

export function PaymentAdminDetailsPage() {
  const demo = useLocation().pathname.startsWith('/demo/'); const id = Number(useParams().id); const [item,setItem] = useState<AdminPayment | null>(null); const [error, setError] = useState('');
  useEffect(() => { api.getAdminPayment(id,demo).then(setItem).catch((cause) => setError(userError(cause, 'Не удалось загрузить платёж.'))); }, [id,demo]);
  if (!item) return <main className="admin-page"><div className="loading">{error || 'Загрузка…'}</div></main>;
  return <main className="admin-page"><Link className="back-link" to={`${demo ? '/demo' : ''}/admin/payments`}>← К платежам</Link><section className="admin-detail payment-admin-detail"><div><p className="eyebrow">Платёж №{item.id}</p><h1>{item.listing?.title ?? `Объявление №${item.listingId}`}</h1><p className="details-price">{formatMoneyMinor(item.amountMinor,item.currency)}</p><dl className="admin-specs"><div><dt>Статус</dt><dd>{PAYMENT_STATUS_LABELS[item.status]}</dd></div><div><dt>Тариф размещения</dt><dd>{item.tariff.name} · {item.tariff.durationDays} дней</dd></div><div><dt>Тип оплаты</dt><dd>{providerLabel(item.provider)}</dd></div><div><dt>ID в платёжной системе</dt><dd>{item.providerPaymentId ?? '—'}</dd></div><div><dt>Ключ запроса</dt><dd className="wrap-value">{item.idempotencyKey}</dd></div><div><dt>Пользователь</dt><dd>{item.customer?.name ?? `№${item.customerId}`}</dd></div></dl></div><aside className="moderation-panel"><h2>События оплаты</h2>{item.events.length ? item.events.map((event) => <div className="history-event" key={event.id}><strong>{PAYMENT_STATUS_LABELS[event.status]}</strong><span>{new Date(event.createdAt).toLocaleString('ru-RU')}</span><small>{event.providerEventId}</small></div>) : <p className="muted">Событий пока нет.</p>}{demo && <p className="demo-notice">Демонстрационный кабинет доступен только для чтения.</p>}</aside></section></main>;
}
