import type { DemoTourDefinition } from './types';

export const automotiveDemoTour: DemoTourDefinition = {
  id: 'automotive-sales-demo',
  storageKey: 'automotive-sales-demo-tour',
  intro: {
    title: 'Посмотрите ключевые возможности AutoMarket',
    lead: 'Короткий тур пройдёт по живому интерфейсу покупателя, продавца и администратора. Данные не будут изменены.',
    bullets: [
      'Каталог и карточка автомобиля',
      'Размещение, фотографии и тариф',
      'Оплата, модерация и demo-админка',
    ],
    startLabel: 'Начать тур',
    skipLabel: 'Смотреть самостоятельно',
  },
  finish: {
    title: 'Демо завершено',
    lead: 'Вы посмотрели полный путь автомобильного объявления — от каталога до административного кабинета.',
    bullets: [
      'Каталог и избранное',
      'Размещение и личный кабинет',
      'Фотографии и предпросмотр',
      'Тариф, оплата и модерация',
      'Административный кабинет',
    ],
    adminLabel: 'Посмотреть demo-админку',
    continueLabel: 'Вернуться в каталог',
  },
  steps: [
    {
      id: 'catalog',
      target: 'catalog-tools',
      route: '/',
      title: 'Каталог автомобилей',
      description: 'Покупатель может смотреть объявления, фильтровать автомобили по основным параметрам и сортировать результаты.',
    },
    {
      id: 'listing-card',
      target: 'catalog-card',
      route: '/',
      title: 'Карточка автомобиля',
      description: 'В карточке сразу видны фото, цена, год, пробег, основные характеристики и город.',
      nextLabel: 'Открыть карточку',
    },
    {
      id: 'favorite',
      target: 'favorite-action',
      action: 'open-listing',
      title: 'Избранное',
      description: 'Пользователь может сохранять интересующие автомобили и возвращаться к ним позже. Тур ничего не добавляет автоматически.',
    },
    {
      id: 'seller-cabinet',
      target: 'seller-cabinet',
      action: 'open-seller-cabinet',
      title: 'Кабинет продавца',
      description: 'Здесь продавец управляет объявлениями и видит этапы: черновик, оплата, модерация, публикация, отклонение и архив.',
    },
    {
      id: 'listing-editor',
      target: 'listing-editor',
      action: 'open-editor-details',
      title: 'Размещение автомобиля',
      description: 'Пошаговая форма сохраняет контекст: характеристики, условия продажи, фотографии и предпросмотр перед размещением.',
    },
    {
      id: 'photos-preview',
      target: 'listing-preview',
      action: 'open-editor-preview',
      scrollBlock: 'start',
      title: 'Фотографии и предпросмотр',
      description: 'Можно добавить до 10 фотографий и проверить, как объявление будет выглядеть перед публикацией. Тур не загружает файлы.',
    },
    {
      id: 'tariff-payment',
      target: 'tariff-selection',
      action: 'open-editor-payment',
      title: 'Тариф размещения и оплата',
      description: 'В демо используется имитация оплаты. Реальный платёжный провайдер подключается отдельно, а тур не создаёт платежи.',
    },
    {
      id: 'moderation',
      target: 'moderation-status',
      action: 'open-moderation',
      title: 'Модерация объявления',
      description: 'После оплаты объявление проходит проверку: на модерации → одобрено или отклонено → публикация. Причина отклонения видна продавцу.',
    },
    {
      id: 'demo-admin',
      target: 'admin-overview',
      action: 'open-demo-admin',
      title: 'Кабинет администратора',
      description: 'Это read-only версия кабинета с объявлениями, статусами и платежами. Полноценная модерация доступна отдельно по защищённому тестовому токену.',
      nextLabel: 'Завершить',
    },
  ],
};
